### ISSUE TITLE
Provisions for return postage on Read operations

### ISSUE THREAD

**Issue by dmitrizagidulin** [rhiaro/didm-snail#4]
Implementor feedback: 
On a Read operation to a `did:snail` address residing in another country from the sender, the spec needs to accommodate the fact that the sender won't be able to stamp the return envelope (since they might not have access to the remote jurisdiction's stamps). 
I realize that postage payment negotiations are likely out of scope for this spec. But it should at least make provisions for making return envelope stamping optional.

**Comment by rhiaro** [comment]
Yep definitely, we can make the stamping of the return addressed envelope an *IF-MUST* or a *SHOULD*
